### ISSUE TITLE
关于5567的黑果

### ISSUE THREAD

**Issue by pzhezhezhe** [kauefontes/INSPIRON-5567-HIGH-SIERRA#1]
想问一下您的efi是支持什么版本 您没有说清楚 我和您配置一样 可以加个微信问问吗

**Comment by kauefontes** [comment]
Hey bro, i droped this project and installed MacOs Mojave.

Please refer to this project: [https://github.com/kauefontes/INSPIRON-5567-MOJAVE](url)

Any doubt, you can ask there(preferably in english, so anyone can help you)

**Comment by pzhezhezhe** [comment]
Does he support any version in your mind, such as 10.13.2 10.13.4?

**Comment by pzhezhezhe** [comment]
I want to know which version of your EFI corresponds to.  thankyou

**Comment by pzhezhezhe** [comment]
I can't express well in English. I'm sorry.

**Comment by kauefontes** [comment]
In this repository my EFI is configured to the latest version ofHigh Sierra(probably 10.13.4).

Google translator usually helps, so everyone can easily find the link related to your question. :smile:

**Comment by kauefontes** [comment]
The other repository that I put the link is for MacOs Mojave(10.14)

**Comment by pzhezhezhe** [comment]
10.13.4 Is there something imperfect?
Thanks for sharing, I will try to install

**Comment by pzhezhezhe** [comment]
are you  have  new  version ？？，i want  try it。 thankyou

**Comment by kauefontes** [comment]
I have the mojave version, you can give it a try
